# Generated by Django 5.0.2 on 2024-02-19 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('roll_number', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='mobile number must be at least 10 digit long'), django.core.validators.RegexValidator('^9\\d{9}$', message='mobile number must be start with 9 and be digit long.')])),
                ('image', models.ImageField(upload_to='Images')),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
